<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T1tjhsp' shared service.

return $this->privates['.service_locator.T1tjhsp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CampaignController::delete' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController::edit' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController::show' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:delete' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:edit' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:show' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
], [
    'App\\Controller\\CampaignController::delete' => '?',
    'App\\Controller\\CampaignController::edit' => '?',
    'App\\Controller\\CampaignController::show' => '?',
    'App\\Controller\\CampaignController:delete' => '?',
    'App\\Controller\\CampaignController:edit' => '?',
    'App\\Controller\\CampaignController:show' => '?',
]);
