<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVRE1pwY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVRE1pwY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVRE1pwY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVRE1pwY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVRE1pwY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VRE1pwY',
    'container.build_id' => '156b1d82',
    'container.build_time' => 1561724083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVRE1pwY');
